version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    networks:
      - app-network
  
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/var/www
    networks:
      - app-network
    depends_on:
      - db

  webserver:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www
    networks:
      - app-network
    depends_on:
      - backend

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: shop_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db-data:
  node_modules:

networks:
  app-network:
    driver: bridge
